---
- name: copy big-service app
  copy: src=panda-service-app dest=/tmp/ owner=root group=root mode=755

- name: copy init script
  copy: src=init dest=/etc/init.d/panda-service-app group=root mode=755

- name: Start big-service-App
  service: name=panda-service-app state=started

- name: Enable big-service-App
  service: name=panda-service-app enabled=yes